#!/usr/bin/env tsx
/**
 * build.ts
 *
 * Reads the TypeScript token modules and emits:
 *   - apps/web/src/styles/tokens.css   — CSS variables (single source of truth at runtime)
 *   - docs/claude/design-system.html   — self-contained visual reference
 *
 * Run:  pnpm tokens:build
 */
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  colors, fonts, fontSizes, fontWeights, lineHeights, letterSpacings,
  space, radii, borderWidths, shadows, durations, easings,
  light, dark, themes,
  textStyles,
  type SemanticPalette,
} from './index';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO = path.resolve(__dirname, '../../../../..');
const CSS_OUT = path.join(REPO, 'apps/web/src/styles/tokens.css');
const HTML_OUT = path.join(REPO, 'docs/claude/design-system.html');

// ─── helpers ─────────────────────────────────────────────────────────
const kebab = (s: string) =>
  s.replace(/[A-Z]/g, (m) => '-' + m.toLowerCase()).replace(/[._]/g, '-');

function flatten(obj: Record<string, unknown>, prefix = ''): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(obj)) {
    const key = prefix ? `${prefix}-${kebab(k)}` : kebab(k);
    if (v && typeof v === 'object' && !Array.isArray(v)) {
      Object.assign(out, flatten(v as Record<string, unknown>, key));
    } else {
      out[key] = String(v);
    }
  }
  return out;
}

function emitCssBlock(name: string, vars: Record<string, string>): string {
  const lines = [`  /* ${name} */`];
  for (const [k, v] of Object.entries(vars)) {
    lines.push(`  --${k}: ${v};`);
  }
  return lines.join('\n');
}

function paletteToCssVars(p: SemanticPalette): Record<string, string> {
  return flatten(p as unknown as Record<string, unknown>);
}

// ─── build CSS ───────────────────────────────────────────────────────
async function buildCss() {
  const base = [
    emitCssBlock('colors', flatten(colors as unknown as Record<string, unknown>, 'color')),
    emitCssBlock('font sizes', flatten(fontSizes as unknown as Record<string, unknown>, 'fs')),
    emitCssBlock('font weights', flatten(fontWeights as unknown as Record<string, unknown>, 'fw')),
    emitCssBlock('line heights', flatten(lineHeights as unknown as Record<string, unknown>, 'lh')),
    emitCssBlock('letter spacings', flatten(letterSpacings as unknown as Record<string, unknown>, 'ls')),
    emitCssBlock('space', flatten(space as unknown as Record<string, unknown>, 'space')),
    emitCssBlock('radii', flatten(radii as unknown as Record<string, unknown>, 'radius')),
    emitCssBlock('border widths', flatten(borderWidths as unknown as Record<string, unknown>, 'bw')),
    emitCssBlock('shadows', flatten(shadows as unknown as Record<string, unknown>, 'shadow')),
    emitCssBlock('durations', flatten(durations as unknown as Record<string, unknown>, 'dur')),
    emitCssBlock('easings', flatten(easings as unknown as Record<string, unknown>, 'ease')),
    `  /* fonts */`,
    `  --font-sans: ${fonts.sans};`,
    `  --font-display: ${fonts.display};`,
    `  --font-serif: ${fonts.serif};`,
    `  --font-mono: ${fonts.mono};`,
  ].join('\n');

  const lightVars = paletteToCssVars(light);
  const darkVars = paletteToCssVars(dark);

  const lightBlock = Object.entries(lightVars)
    .map(([k, v]) => `  --${k}: ${v};`)
    .join('\n');
  const darkBlock = Object.entries(darkVars)
    .map(([k, v]) => `  --${k}: ${v};`)
    .join('\n');

  const css = `/* Auto-generated by apps/web/src/styles/tokens/build.ts.
   DO NOT edit by hand — change the TS source modules and run \`pnpm tokens:build\`. */

:root {
${base}

  /* ─── semantic (light) ─── */
${lightBlock}
}

[data-theme='dark'] {
${darkBlock}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${darkBlock}
  }
}
`;

  await fs.mkdir(path.dirname(CSS_OUT), { recursive: true });
  await fs.writeFile(CSS_OUT, css);
  console.log(`✓ wrote ${path.relative(REPO, CSS_OUT)}`);
}

// ─── build HTML doc ──────────────────────────────────────────────────
const isDarkColor = (hex: string): boolean => {
  const m = hex.match(/^#([0-9a-f]{6})/i);
  if (!m) return false;
  const c = m[1]!;
  const r = parseInt(c.slice(0, 2), 16);
  const g = parseInt(c.slice(2, 4), 16);
  const b = parseInt(c.slice(4, 6), 16);
  return (r * 299 + g * 587 + b * 114) / 1000 < 140;
};

function colorScale(name: string, scale: Record<string, string>): string {
  const swatches = Object.entries(scale)
    .map(([k, v]) => {
      const dark = isDarkColor(v);
      return `<div class="sw" style="background:${v};color:${dark ? '#fff' : '#000'}">
        <span class="sw-name">${k}</span>
        <code>${v}</code>
      </div>`;
    })
    .join('');
  return `<section class="block">
    <h3>${name}</h3>
    <div class="scale">${swatches}</div>
  </section>`;
}

function semanticGroup(group: string, items: Record<string, string | Record<string, string>>): string {
  const rows: string[] = [];
  for (const [k, v] of Object.entries(items)) {
    if (typeof v === 'string') {
      const isColor = /^#|^rgb/.test(v);
      const preview = isColor
        ? `<span class="chip" style="background:${v}"></span>`
        : '';
      rows.push(`<tr>
        <td><code class="token-name">${group}.${k}</code></td>
        <td>${preview}</td>
        <td><code class="hex">${v}</code></td>
      </tr>`);
    } else {
      for (const [sk, sv] of Object.entries(v)) {
        const preview = `<span class="chip" style="background:${sv}"></span>`;
        rows.push(`<tr>
          <td><code class="token-name">${group}.${k}.${sk}</code></td>
          <td>${preview}</td>
          <td><code class="hex">${sv}</code></td>
        </tr>`);
      }
    }
  }
  return `<section class="block"><h3>${group}</h3><table>${rows.join('')}</table></section>`;
}

function textStyleSpec(): string {
  const rows = Object.entries(textStyles)
    .map(([name, s]) => {
      return `<div class="ts-row">
        <div class="ts-meta">
          <code class="ts-name">${name}</code>
          <code class="ts-rule">${s.fontSize} · ${s.fontWeight} · ${s.lineHeight}</code>
        </div>
        <div class="ts-sample" style="font-family:${s.fontFamily};font-size:${s.fontSize};font-weight:${s.fontWeight};line-height:${s.lineHeight};letter-spacing:${s.letterSpacing ?? '0'};text-transform:${s.textTransform ?? 'none'}">
          教师批改 — Teacher Score · The quick brown fox
        </div>
      </div>`;
    })
    .join('');
  return `<section class="block">
    <div class="ts-list">${rows}</div>
  </section>`;
}

function sizingTable(name: string, items: Record<string, string>): string {
  const rows = Object.entries(items)
    .map(([k, v]) => `<tr><td><code class="token-name">${name}.${k}</code></td><td class="hex">${v}</td></tr>`)
    .join('');
  return `<section class="block"><h3>${name}</h3><table class="num-table">${rows}</table></section>`;
}

function radiiCards(): string {
  const items = Object.entries(radii)
    .map(([k, v]) => `<div class="radius-card" style="border-radius:${v}">
      <span>${k}</span><code>${v}</code>
    </div>`)
    .join('');
  return `<section class="block"><h3>radii</h3><div class="radii-row">${items}</div></section>`;
}

function components(): string {
  return `<section class="block">
    <h4>Buttons</h4>
    <div class="row">
      <button class="btn btn-primary">主操作</button>
      <button class="btn btn-secondary">次操作</button>
      <button class="btn btn-ghost">幽灵按钮</button>
      <button class="btn btn-danger">删除</button>
    </div>

    <h4 style="margin-top:24px">Badges</h4>
    <div class="row">
      <span class="badge badge-info">info</span>
      <span class="badge badge-success">success</span>
      <span class="badge badge-warning">warning</span>
      <span class="badge badge-danger">danger</span>
      <span class="badge badge-neutral">neutral</span>
    </div>

    <h4 style="margin-top:24px">Card</h4>
    <div class="card">
      <p class="overline">eyebrow · 卡片标签</p>
      <h5 style="font-family:${fonts.sans};font-weight:600;font-size:${fontSizes['2xl']};margin:0 0 8px">学生张三 · 数学</h5>
      <p style="font-family:${fonts.sans};color:${light.fg.muted};margin:0 0 16px;line-height:${lineHeights.relaxed}">
        正文使用 fg.muted (${light.fg.muted})。卡片用 bg.surface + border.default。
      </p>
      <div class="row">
        <button class="btn btn-primary">查看详情</button>
        <button class="btn btn-ghost">编辑</button>
      </div>
    </div>
  </section>`;
}

async function buildHtml() {
  const html = `<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<title>Design System — 教师批改</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600;700&family=Poppins:wght@400;500;600;700&family=Source+Serif+4:opsz,wght@8..60,400;8..60,600&family=JetBrains+Mono:wght@400;500;600&display=swap" rel="stylesheet">
<style>
:root {
${Object.entries(paletteToCssVars(light)).map(([k, v]) => `  --${k}: ${v};`).join('\n')}
}
* { box-sizing: border-box; }
body {
  margin: 0;
  background: ${light.bg.canvas};
  color: ${light.fg.default};
  font-family: 'Open Sans', system-ui, sans-serif;
  font-size: 14px;
  line-height: 1.5;
  -webkit-font-smoothing: antialiased;
}
.app { max-width: 1080px; margin: 0 auto; padding: 56px 32px 80px; }
.brand { display: flex; align-items: baseline; gap: 16px; margin-bottom: 32px; padding-bottom: 24px; border-bottom: 1px solid ${light.border.default}; }
.brand h1 { font-family: 'Poppins'; font-weight: 600; font-size: 32px; margin: 0; letter-spacing: -0.02em; }
.brand .sub { color: ${light.fg.subtle}; font-family: 'JetBrains Mono'; font-size: 12px; }
.intro { background: ${light.bg.surface}; border: 1px solid ${light.border.default}; border-radius: 12px; padding: 24px; margin-bottom: 48px; }
.intro h2 { font-family: 'Source Serif 4'; font-weight: 600; font-size: 22px; margin: 0 0 12px; }
.intro p { margin: 0 0 8px; color: ${light.fg.muted}; line-height: 1.65; }
.intro code { font-family: 'JetBrains Mono'; font-size: 13px; background: ${light.bg.muted}; padding: 1px 6px; border-radius: 4px; }
.toc { display: flex; flex-wrap: wrap; gap: 16px 24px; margin-bottom: 48px; font-family: 'JetBrains Mono'; font-size: 12px; }
.toc a { color: ${light.fg.brand}; text-decoration: none; }
.toc a:hover { text-decoration: underline; }
h2.section { font-family: 'Source Serif 4'; font-weight: 600; font-size: 28px; margin: 56px 0 24px; padding-bottom: 12px; border-bottom: 1px solid ${light.border.default}; letter-spacing: -0.01em; }
.block { margin-bottom: 48px; }
.block h3 { font-family: 'Open Sans'; font-weight: 600; font-size: 18px; margin: 0 0 14px; }
.block h4 { font-family: 'Open Sans'; font-weight: 600; font-size: 14px; margin: 0 0 10px; color: ${light.fg.muted}; }
.scale {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(96px, 1fr));
  gap: 1px;
  border: 1px solid ${light.border.default};
  background: ${light.border.default};
  border-radius: 8px;
  overflow: hidden;
}
.sw { padding: 14px 10px 10px; display: flex; flex-direction: column; gap: 2px; font-size: 11px; }
.sw-name { font-family: 'Open Sans'; font-weight: 600; font-size: 12px; }
.sw code { font-family: 'JetBrains Mono'; font-size: 10px; opacity: 0.75; }
table { width: 100%; border-collapse: collapse; font-size: 13px; }
table td { padding: 8px 12px; border-bottom: 1px solid ${light.border.subtle}; vertical-align: middle; }
.token-name { font-family: 'JetBrains Mono'; font-size: 12px; color: ${light.fg.default}; font-weight: 500; }
.hex { font-family: 'JetBrains Mono'; font-size: 12px; color: ${light.fg.subtle}; }
.chip { display: inline-block; width: 32px; height: 18px; border-radius: 4px; border: 1px solid ${light.border.default}; vertical-align: middle; }
.num-table td:nth-child(2) { text-align: right; font-family: 'JetBrains Mono'; }
.radii-row { display: flex; gap: 12px; flex-wrap: wrap; }
.radius-card {
  width: 96px; height: 96px;
  background: ${light.bg.muted};
  border: 1px solid ${light.border.default};
  display: flex; flex-direction: column; align-items: center; justify-content: center;
  gap: 4px;
}
.radius-card span { font-family: 'Open Sans'; font-weight: 600; font-size: 13px; }
.radius-card code { font-family: 'JetBrains Mono'; font-size: 11px; color: ${light.fg.subtle}; }
.ts-list { display: flex; flex-direction: column; gap: 12px; }
.ts-row { display: grid; grid-template-columns: 220px 1fr; gap: 24px; padding: 12px 0; border-bottom: 1px solid ${light.border.subtle}; align-items: baseline; }
.ts-meta { display: flex; flex-direction: column; gap: 4px; }
.ts-name { font-family: 'JetBrains Mono'; font-size: 12px; font-weight: 600; color: ${light.fg.default}; }
.ts-rule { font-family: 'JetBrains Mono'; font-size: 10px; color: ${light.fg.subtle}; }
.row { display: flex; gap: 12px; flex-wrap: wrap; align-items: center; }
.btn { font-family: 'Open Sans'; font-weight: 500; font-size: 14px; padding: 8px 16px; border-radius: 8px; border: 1px solid transparent; cursor: pointer; transition: all 120ms ease; }
.btn-primary { background: ${light.interactive.primary.bg}; color: ${light.interactive.primary.fg}; }
.btn-primary:hover { background: ${light.interactive.primary.bgHover}; }
.btn-secondary { background: ${light.interactive.secondary.bg}; color: ${light.interactive.secondary.fg}; border-color: ${light.interactive.secondary.border}; }
.btn-secondary:hover { background: ${light.interactive.secondary.bgHover}; }
.btn-ghost { background: ${light.interactive.ghost.bg}; color: ${light.interactive.ghost.fg}; }
.btn-ghost:hover { background: ${light.interactive.ghost.bgHover}; }
.btn-danger { background: ${light.interactive.danger.bg}; color: ${light.interactive.danger.fg}; }
.btn-danger:hover { background: ${light.interactive.danger.bgHover}; }
.badge { font-family: 'Open Sans'; font-size: 12px; padding: 3px 8px; border-radius: 4px; font-weight: 500; }
.badge-info { background: ${light.status.info.bg}; color: ${light.status.info.fg}; }
.badge-success { background: ${light.status.success.bg}; color: ${light.status.success.fg}; }
.badge-warning { background: ${light.status.warning.bg}; color: ${light.status.warning.fg}; }
.badge-danger { background: ${light.status.danger.bg}; color: ${light.status.danger.fg}; }
.badge-neutral { background: ${light.status.neutral.bg}; color: ${light.status.neutral.fg}; }
.card { background: ${light.bg.surface}; border: 1px solid ${light.border.default}; border-radius: 12px; padding: 20px; max-width: 480px; }
.overline { font-family: 'JetBrains Mono'; font-size: 11px; font-weight: 600; letter-spacing: 0.12em; text-transform: uppercase; color: ${light.fg.subtle}; margin: 0 0 8px; }
</style>
</head>
<body>
<div class="app">
  <header class="brand">
    <h1>Design System · 教师批改</h1>
    <span class="sub">v1 · generated from apps/web/src/styles/tokens/*.ts</span>
  </header>

  <div class="intro">
    <h2>两层架构</h2>
    <p><strong>Base tokens</strong>（<code>base.ts</code>）—— 原料：色阶、字体、字号、间距、圆角等。业务代码<strong>不</strong>直接使用。</p>
    <p><strong>Semantic tokens</strong>（<code>semantic.ts</code>）—— 语义化命名：<code>bg.canvas</code>、<code>fg.default</code>、<code>interactive.primary.bg</code>。<strong>所有组件 / 页面只用这一层</strong>。切换 light/dark 主题只需重新映射这一层，业务代码零修改。</p>
    <p><strong>Text styles</strong>（<code>text-styles.ts</code>）—— 命名组合样式：<code>display.lg</code>、<code>body.md</code>、<code>overline</code>。JSX 里 <code>&lt;Text textStyle="body.md"&gt;</code> 直接引用。</p>
    <p style="margin-top:16px">改 token 后跑 <code>pnpm tokens:build</code> 重新生成 CSS 变量和这份文档。</p>
  </div>

  <nav class="toc">
    <a href="#semantic">语义化 tokens</a>
    <a href="#text-styles">textStyles</a>
    <a href="#components">组件样例</a>
    <a href="#scales">色阶（base）</a>
    <a href="#sizing">间距 / 圆角 / 边框</a>
  </nav>

  <h2 id="semantic" class="section">语义化 tokens —— 业务代码用这些</h2>
  ${semanticGroup('bg', light.bg)}
  ${semanticGroup('fg', light.fg)}
  ${semanticGroup('border', light.border)}
  ${semanticGroup('interactive', light.interactive as unknown as Record<string, Record<string, string>>)}
  ${semanticGroup('status', light.status as unknown as Record<string, Record<string, string>>)}

  <h2 id="text-styles" class="section">textStyles</h2>
  ${textStyleSpec()}

  <h2 id="components" class="section">组件样例</h2>
  ${components()}

  <h2 id="scales" class="section">色阶（base —— 给 semantic 引用，不直接用）</h2>
  ${Object.entries(colors).filter(([, v]) => typeof v === 'object').map(([k, v]) => colorScale(k, v as Record<string, string>)).join('')}

  <h2 id="sizing" class="section">间距 · 圆角 · 边框</h2>
  ${sizingTable('space', space)}
  ${radiiCards()}
  ${sizingTable('borderWidths', borderWidths)}
  ${sizingTable('shadows', shadows)}

  <footer style="margin-top:80px;padding-top:24px;border-top:1px solid ${light.border.default};font-family:'JetBrains Mono';font-size:11px;color:${light.fg.subtle}">
    生成自 <code>apps/web/src/styles/tokens/*.ts</code> · 修改后跑 <code>pnpm tokens:build</code> 重新生成
  </footer>
</div>
</body>
</html>`;

  await fs.mkdir(path.dirname(HTML_OUT), { recursive: true });
  await fs.writeFile(HTML_OUT, html);
  console.log(`✓ wrote ${path.relative(REPO, HTML_OUT)}`);
}

// ─── go ──────────────────────────────────────────────────────────────
async function main() {
  await buildCss();
  await buildHtml();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
